### ISSUE TITLE
mnelab crashes on Windows 11 with ImportError: DLL load failed while importing QtCore

### ISSUE THREAD

**Issue by joschaschmiedt** [neuro-conda/neuro-conda#30]
On Windows 11 with neuro-conda 35c6d6ff96dc4949fade6191bb07701f3f519b00, mnelab 0.8.5 crashes at startup with 

```
Traceback (most recent call last):
  File "C:\Users\Public\miniconda3\envs\neuro-conda-2023a\Scripts\mnelab-script.py", line 6, in <module>
    from mnelab.__main__ import main
  File "C:\Users\Public\miniconda3\envs\neuro-conda-2023a\lib\site-packages\mnelab\__init__.py", line 10, in <module>
    from PySide6.QtCore import Qt
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
```

<details>
<summary>Installed packages</summary>

```
# packages in environment at C:\Users\Public\miniconda3\envs\neuro-conda-2023a:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1
aiohttp                   3.8.3           py310h2bbff1b_0
aiosignal                 1.2.0              pyhd3eb1b0_0
alabaster                 0.7.13                   pypi_0    pypi
anyio                     3.5.0           py310haa95532_0
aom                       3.5.0                h63175ca_0    conda-forge
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0          py310h2bbff1b_0
arrow                     1.2.3           py310haa95532_1
asciitree                 0.3.3                    pypi_0    pypi
assimp                    5.2.3                hc2aa0de_1    conda-forge
astor                     0.8.1                    pypi_0    pypi
astroid                   2.14.2          py310haa95532_0
asttokens                 2.0.5              pyhd3eb1b0_0
async-timeout             4.0.2           py310haa95532_0
atomicwrites              1.4.0                      py_0
attrs                     22.1.0          py310haa95532_0
autopep8                  1.6.0              pyhd3eb1b0_1
autoreject                0.4.1              pyhd8ed1ab_0    conda-forge
babel                     2.11.0          py310haa95532_0
backcall                  0.2.0              pyhd3eb1b0_0
bcrypt                    3.2.0           py310h2bbff1b_1
beautifulsoup4            4.11.1          py310haa95532_0
bids-validator            1.10.0                   pypi_0    pypi
binaryornot               0.4.4              pyhd3eb1b0_1
black                     22.6.0          py310haa95532_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
blosc                     1.21.3               h6c2663c_0
bokeh                     2.4.3           py310haa95532_0
boost-cpp                 1.74.0               h9f4b32c_8    conda-forge
bottleneck                1.3.5           py310h9128911_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py310h2bbff1b_1002
bycycle                   1.0.0                    pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2023.01.10           haa95532_0
cached-property           1.5.2                      py_0
cairo                     1.16.0               h1c23506_3
certifi                   2022.12.7       py310haa95532_0
cffi                      1.15.1          py310h2bbff1b_3
cfitsio                   3.470                h2bbff1b_7
cftime                    1.5.1.1         py310h9128911_0
chardet                   4.0.0           py310haa95532_1003
charls                    2.2.0                h6c2663c_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
ci-info                   0.3.0                    pypi_0    pypi
click                     8.0.4           py310haa95532_0
cloudpickle               2.0.0              pyhd3eb1b0_0
colorama                  0.4.6           py310haa95532_0
coloredlogs               15.0.1          py310haa95532_1
colorspacious             1.1.2              pyh24bf2e0_0    conda-forge
comm                      0.1.2           py310haa95532_0
contourpy                 1.0.5           py310h59b6b97_0
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              39.0.1          py310h21b164f_0
curl                      7.87.0               h2bbff1b_0
cycler                    0.11.0             pyhd3eb1b0_0
cython                    0.29.33         py310hd77b12b_0
cytoolz                   0.12.0          py310h2bbff1b_0
darkdetect                0.8.0              pyhd8ed1ab_0    conda-forge
dask                      2022.10.2                pypi_0    pypi
dask-jobqueue             0.8.1                    pypi_0    pypi
dataconf                  2.1.3                    pypi_0    pypi
debugpy                   1.5.1           py310hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
deid                      0.3.21             pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.6           py310haa95532_0
dipy                      1.5.0           py310h0032c74_2    conda-forge
distinctipy               1.2.2                    pypi_0    pypi
distributed               2022.10.2                pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
docstring-to-markdown     0.11            py310haa95532_0
docutils                  0.19                     pypi_0    pypi
double-conversion         3.2.0                h63175ca_1    conda-forge
edflib-python             1.0.6              pyhd8ed1ab_0    conda-forge
eigen                     3.3.7                h59b6b97_1
elephant                  0.11.2                   pypi_0    pypi
entrypoints               0.4             py310haa95532_0
esi-acme                  2022.12                  pypi_0    pypi
esi-syncopy               2022.12                  pypi_0    pypi
et_xmlfile                1.1.0           py310haa95532_0
etelemetry                0.3.0                    pypi_0    pypi
exceptiongroup            1.1.0                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0
expat                     2.4.9                h6c2663c_0
fasteners                 0.18                     pypi_0    pypi
ffmpeg                    4.4.2           gpl_h02edd2a_109    conda-forge
filelock                  3.9.0           py310haa95532_0
flake8                    6.0.0           py310haa95532_0
flit-core                 3.6.0              pyhd3eb1b0_0
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                hd3eb1b0_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fontconfig                2.14.1               hc0defaf_1
fonts-anaconda            1                    h8fa9717_0
fonts-conda-ecosystem     1                    hd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
fooof                     1.0.0                    pypi_0    pypi
formulaic                 0.5.2                    pypi_0    pypi
freetype                  2.12.1               ha860e81_0
frozenlist                1.3.3           py310h2bbff1b_0
fsspec                    2022.11.0       py310haa95532_0
future                    0.18.3          py310haa95532_0
gettext                   0.21.1               h5728263_0    conda-forge
giflib                    5.2.1                h8cc25b3_3
gl2ps                     1.4.2                hce2df77_1
glew                      2.1.0                hd77b12b_3
glib                      2.74.1               h12be248_0    conda-forge
glib-tools                2.74.1               h12be248_0    conda-forge
graphite2                 1.3.14               hd77b12b_1
gst-plugins-base          1.20.3               h001b923_2    conda-forge
gstreamer                 1.20.3               h6b5321d_2    conda-forge
h5io                      0.1.7              pyh8a188c0_0    conda-forge
h5netcdf                  1.1.0              pyhd8ed1ab_1    conda-forge
h5py                      3.8.0           nompi_py310hae7a582_100    conda-forge
harfbuzz                  5.3.0                he256f1b_0    conda-forge
hdf4                      4.2.15               h1b1b6ef_5    conda-forge
hdf5                      1.12.2          nompi_h2a0e4a3_101    conda-forge
hdmf                      3.5.1                    pypi_0    pypi
heapdict                  1.0.1              pyhd3eb1b0_0
humanfriendly             10.0            py310haa95532_1
icc_rt                    2022.1.0             h6049295_2
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4             py310haa95532_0
imagecodecs               2021.8.26       py310h6e7a67f_1
imageio                   2.26.0          py310haa95532_0
imagesize                 1.4.1           py310haa95532_0
importlib-metadata        4.11.3          py310haa95532_0
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_metadata        4.11.3               hd3eb1b0_0
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
inflection                0.5.1           py310haa95532_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2021.4.0          haa95532_3556
intensity-normalization   2.1.4              pyhd8ed1ab_0    conda-forge
interface-meta            1.3.0                    pypi_0    pypi
intervaltree              3.1.0              pyhd3eb1b0_0
ipdb                      0.13.11                  pypi_0    pypi
ipycanvas                 0.13.1             pyhd8ed1ab_0    conda-forge
ipyevents                 2.0.1              pyhd8ed1ab_0    conda-forge
ipykernel                 6.19.2          py310h9909e9c_0
ipympl                    0.8.7              pyhd3eb1b0_0
ipython                   8.10.0          py310haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipyvtklink                0.2.3              pyhd8ed1ab_0    conda-forge
ipywidgets                7.6.5              pyhd3eb1b0_1
isodate                   0.6.1                    pypi_0    pypi
isort                     5.9.3              pyhd3eb1b0_0
jedi                      0.18.1          py310haa95532_1
jellyfish                 0.9.0           py310h2bbff1b_0
jinja2                    3.1.2           py310haa95532_0
jinja2-time               0.2.0              pyhd3eb1b0_3
joblib                    1.1.1           py310haa95532_0
jpeg                      9e                   h2bbff1b_1
json5                     0.9.6              pyhd3eb1b0_0
json_tricks               3.16.1             pyhd8ed1ab_0    conda-forge
jsoncpp                   1.9.5                h2d74725_1    conda-forge
jsonschema                4.17.3          py310haa95532_0
jupyter                   1.0.0           py310haa95532_8
jupyter-server-proxy      3.2.2              pyhd8ed1ab_0    conda-forge
jupyter_client            7.3.4           py310haa95532_0
jupyter_console           6.6.2           py310haa95532_0
jupyter_core              5.2.0           py310haa95532_0
jupyter_server            1.23.4          py310haa95532_0
jupyterlab                3.5.3           py310haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.19.0          py310haa95532_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
keyring                   23.4.0          py310haa95532_0
kiwisolver                1.4.4           py310hd77b12b_0
krb5                      1.19.4               h5b6d351_0
lazy-loader               0.1                      pypi_0    pypi
lazy-object-proxy         1.6.0           py310h2bbff1b_0
lcms2                     2.12                 h83e58a3_0
lerc                      3.0                  hd77b12b_0
libaec                    1.0.6                h63175ca_1    conda-forge
libblas                   3.9.0           1_h8933c1f_netlib    conda-forge
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  14.0.6          default_hf4acfee_0
libclang13                14.0.6          default_h8992b79_0
libcurl                   7.87.0               h86230a5_0
libdeflate                1.8                  h2bbff1b_5
libffi                    3.4.2                hd77b12b_6
libglib                   2.74.1               h79619a9_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0           5_hd5c7e75_netlib    conda-forge
libnetcdf                 4.8.1           nompi_h85765be_104    conda-forge
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.39               h8cc25b3_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               hcd4344a_0
libtheora                 1.1.1                h8cc25b3_3
libtiff                   4.4.0                h8a3f274_2
libuv                     1.44.2               h2bbff1b_0
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                hbc33d0d_1
libwebp-base              1.2.4                h2bbff1b_1
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
libzip                    1.9.2                hfed4ece_1    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
libzopfli                 1.0.3                ha925a31_0
llvmlite                  0.39.1          py310h23ce68f_0
locket                    1.0.0           py310haa95532_0
loguru                    0.5.3           py310haa95532_4
looseversion              1.1.2                    pypi_0    pypi
lxml                      4.9.1           py310h1985fb9_0
lz4                       3.1.3           py310h2bbff1b_0
lz4-c                     1.9.4                h2bbff1b_0
m2w64-bwidget             1.9.10                        2
m2w64-bzip2               1.0.6                         6
m2w64-expat               2.1.1                         2
m2w64-fftw                3.3.4                         6
m2w64-flac                1.3.1                         3
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-gsl                 2.1                           2
m2w64-libiconv            1.14                          6
m2w64-libjpeg-turbo       1.4.2                         3
m2w64-libogg              1.3.2                         3
m2w64-libpng              1.6.21                        2
m2w64-libsndfile          1.0.26                        2
m2w64-libtiff             4.0.6                         2
m2w64-libvorbis           1.3.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-libxml2             2.9.3                         4
m2w64-mpfr                3.1.4                         4
m2w64-pcre2               10.34                         0    conda-forge
m2w64-speex               1.2rc2                        3
m2w64-speexdsp            1.2rc3                        3
m2w64-tcl                 8.6.5                         3
m2w64-tk                  8.6.5                         3
m2w64-tktable             2.10                          5
m2w64-wineditline         2.101                         5
m2w64-xz                  5.2.2                         2
m2w64-zlib                1.2.8                        10
markupsafe                2.1.1           py310h2bbff1b_0
matplotlib                3.6.2           py310haa95532_0
matplotlib-base           3.6.2           py310h1094b8e_0
matplotlib-inline         0.1.6           py310haa95532_0
mccabe                    0.7.0              pyhd3eb1b0_0
memory-profiler           0.60.0                   pypi_0    pypi
mistune                   0.8.4           py310h2bbff1b_1000
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0           py310h2bbff1b_0
mkl_fft                   1.3.1           py310ha0764ea_0
mkl_random                1.2.2           py310h4ed8f06_0
mne-ari                   0.1.2              pyhd8ed1ab_0    conda-forge
mne-base                  1.3.1              pyh57928b3_0    conda-forge
mne-bids                  0.12               pyhd8ed1ab_0    conda-forge
mne-bids-pipeline         1.1.0              pyhd8ed1ab_0    conda-forge
mne-connectivity          0.5.0              pyhd8ed1ab_0    conda-forge
mne-features              0.2.1              pyhd8ed1ab_0    conda-forge
mne-icalabel              0.4                pyhd8ed1ab_2    conda-forge
mne-nirs                  0.5.0              pyhd8ed1ab_0    conda-forge
mne-qt-browser            0.4.0           py310h5588dad_0    conda-forge
mne-realtime              0.2.0              pyhd8ed1ab_0    conda-forge
mne-rsa                   0.8                pyhd8ed1ab_0    conda-forge
mnelab                    0.8.5           py310h5588dad_1    conda-forge
mpi                       1.0                       msmpi
mpi4py                    3.1.4           py310hb01be7b_0
msgpack-python            1.0.3           py310h59b6b97_0
msmpi                     10.1.1               had4844c_0
msys2-conda-epoch         20160418                      1
multidict                 6.0.2           py310h2bbff1b_0
munkres                   1.1.4                      py_0
mypy_extensions           0.4.3           py310haa95532_1
napari-nibabel            0.1.0                    pypi_0    pypi
natsort                   8.3.1                    pypi_0    pypi
nbclassic                 0.5.2           py310haa95532_0
nbclient                  0.5.13          py310haa95532_0
nbconvert                 6.5.4           py310haa95532_0
nbformat                  5.7.0           py310haa95532_0
neo                       0.12.0                   pypi_0    pypi
nest-asyncio              1.5.6           py310haa95532_0
netcdf4                   1.6.2           py310hadf358c_0
networkx                  2.8.4           py310haa95532_0
neurodsp                  2.2.1                    pypi_0    pypi
nibabel                   5.0.1              pyhd8ed1ab_0    conda-forge
nilearn                   0.10.0             pyhd8ed1ab_0    conda-forge
ninja                     1.10.2               haa95532_5
ninja-base                1.10.2               h6d14046_5
nipype                    1.8.5                    pypi_0    pypi
nitime                    0.9                      pypi_0    pypi
nixio                     1.5.3                    pypi_0    pypi
nlohmann_json             3.10.5               h6c2663c_0
notebook                  6.5.2           py310haa95532_0
notebook-shim             0.2.2           py310haa95532_0
num2words                 0.5.12                   pypi_0    pypi
numba                     0.56.4          py310h4ed8f06_0
numcodecs                 0.11.0          py310hd77b12b_0
numexpr                   2.8.4           py310hd213c9f_0
numpy                     1.23.5          py310h60c9a35_0
numpy-base                1.23.5          py310h04254f7_0
numpydoc                  1.5.0           py310haa95532_0
openh264                  2.3.1                h63175ca_2    conda-forge
openjpeg                  2.4.0                h4fc8c34_0
openpyxl                  3.0.10          py310h2bbff1b_0
openssl                   1.1.1t               h2bbff1b_0
packaging                 22.0            py310haa95532_0
pandas                    1.5.3           py310h4ed8f06_0
pandocfilters             1.5.0              pyhd3eb1b0_0
paramiko                  2.8.1              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
partd                     1.2.0              pyhd3eb1b0_1
pathspec                  0.10.3          py310haa95532_0
patsy                     0.5.3           py310haa95532_0
pcre2                     10.37                h0ff8eda_1
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.4.0           py310hd77b12b_0
pip                       22.3.1          py310haa95532_0
pixman                    0.40.0               h2bbff1b_1
platformdirs              2.5.2           py310haa95532_0
pluggy                    1.0.0           py310haa95532_1
ply                       3.11            py310haa95532_0
pooch                     1.7.0              pyhd8ed1ab_0    conda-forge
popeye                    1.0.0                    pypi_0    pypi
poyo                      0.5.0              pyhd3eb1b0_0
probeinterface            0.2.16                   pypi_0    pypi
proj                      9.1.0                h3863b3b_0    conda-forge
prometheus_client         0.14.1          py310haa95532_0
prompt-toolkit            3.0.36          py310haa95532_0
prompt_toolkit            3.0.36               hd3eb1b0_0
prov                      2.0.0                    pypi_0    pypi
psutil                    5.9.0           py310h2bbff1b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pugixml                   1.11.4               hd77b12b_1
pure_eval                 0.2.2              pyhd3eb1b0_0
py                        1.11.0             pyhd3eb1b0_0
pybids                    0.15.6                   pypi_0    pypi
pybv                      0.7.5              pyhd8ed1ab_0    conda-forge
pycodestyle               2.10.0          py310haa95532_0
pycparser                 2.21               pyhd3eb1b0_0
pydicom                   2.3.1              pyh1a96a4e_0    conda-forge
pydocstyle                6.3.0           py310haa95532_0
pydot                     1.4.2                    pypi_0    pypi
pyedflib                  0.1.30          py310h9b08ddd_1    conda-forge
pyflakes                  3.0.1           py310haa95532_0
pygments                  2.14.0                   pypi_0    pypi
pyhocon                   0.3.60                   pypi_0    pypi
pylint                    2.16.2          py310haa95532_0
pylint-venv               2.3.0                    pypi_0    pypi
pyls-spyder               0.4.0              pyhd3eb1b0_0
pymatreader               0.0.30             pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0           py310h8cc25b3_0
pynwb                     2.3.1                    pypi_0    pypi
pyopenssl                 23.0.0          py310haa95532_0
pyparsing                 3.0.9           py310haa95532_0
pyqt                      5.15.7          py310hd77b12b_0
pyqt5-sip                 12.11.0         py310hd77b12b_0
pyqtgraph                 0.13.1          py310haa95532_0
pyqtwebengine             5.15.7          py310hd77b12b_0
pyreadline3               3.4.1           py310haa95532_0
pyrsistent                0.18.0          py310h2bbff1b_0
pyside6                   6.4.1           py310h7a8ee39_0    conda-forge
pysocks                   1.7.1           py310haa95532_0
pytables                  3.7.0           py310haee3a42_3    conda-forge
pytest                    7.2.2                    pypi_0    pypi
pytest-runner             6.0.0           py310haa95532_0
python                    3.10.9               h966fe2a_1
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2          py310haa95532_0
python-lsp-black          1.2.1           py310haa95532_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.7.1           py310haa95532_0
python-picard             0.7                pyh8a188c0_0    conda-forge
python-slugify            5.0.2              pyhd3eb1b0_0
python_abi                3.10                    2_cp310    conda-forge
pytoolconfig              1.2.5           py310haa95532_1
pytorch                   1.12.1          cpu_py310h5e1f01c_1
pytz                      2022.7          py310haa95532_0
pyvista                   0.38.3             pyhd8ed1ab_0    conda-forge
pyvistaqt                 0.9.1              pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1           py310h2bbff1b_0
pywin32                   305             py310h2bbff1b_0
pywin32-ctypes            0.2.0           py310haa95532_1000
pywinpty                  2.0.10          py310h5da7b33_0
pyxdf                     1.16.4             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h2bbff1b_1
pyzmq                     23.2.0          py310hd77b12b_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.2.2                    pypi_0    pypi
qt-main                   5.15.6               hf0cf448_0    conda-forge
qt-webengine              5.15.9               hb9a9bb5_5
qt6-main                  6.4.0                he608ae7_3    conda-forge
qtawesome                 1.2.2                    pypi_0    pypi
qtconsole                 5.4.0                    pypi_0    pypi
qtpy                      2.2.0           py310haa95532_0
qtwebkit                  5.212                h0db62b3_6    conda-forge
quantities                0.14.1                   pypi_0    pypi
r-base                    4.1.3                hdca333a_5    conda-forge
r-base64enc               0.1_3           r41h6d2157b_1005    conda-forge
r-cli                     3.6.0             r41ha856d6a_0    conda-forge
r-crayon                  1.5.2             r41hc72bb7e_1    conda-forge
r-digest                  0.6.31            r41ha856d6a_0    conda-forge
r-ellipsis                0.3.2             r41h6d2157b_1    conda-forge
r-evaluate                0.20              r41hc72bb7e_0    conda-forge
r-fansi                   1.0.4             r41h6d2157b_0    conda-forge
r-fastmap                 1.1.1             r41ha856d6a_0    conda-forge
r-glue                    1.6.2             r41h6d2157b_1    conda-forge
r-htmltools               0.5.4             r41ha856d6a_0    conda-forge
r-irdisplay               1.1               r41hd8ed1ab_1    conda-forge
r-irkernel                1.3.2             r41h785f33e_0    conda-forge
r-jsonlite                1.8.4             r41h6d2157b_0    conda-forge
r-lifecycle               1.0.3             r41hc72bb7e_1    conda-forge
r-pbdzmq                  0.3_9             r41hf3fe701_0    conda-forge
r-pillar                  1.8.1             r41hc72bb7e_1    conda-forge
r-repr                    1.1.6             r41h785f33e_0    conda-forge
r-rlang                   1.0.6             r41ha856d6a_1    conda-forge
r-utf8                    1.2.3             r41h6d2157b_0    conda-forge
r-uuid                    1.1_0             r41h6d2157b_1    conda-forge
r-vctrs                   0.5.2             r41ha856d6a_0    conda-forge
rdflib                    6.2.0                    pypi_0    pypi
requests                  2.28.1          py310haa95532_0
rope                      1.7.0           py310haa95532_0
rtree                     1.0.1           py310h2eaa2aa_0
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
scikit-fuzzy              0.4.2                      py_1    conda-forge
scikit-image              0.20.0                   pypi_0    pypi
scikit-learn              1.2.1           py310hd77b12b_0
scipy                     1.10.0          py310hb9afe5d_1
scooby                    0.7.1              pyhd8ed1ab_0    conda-forge
seaborn                   0.12.2          py310haa95532_0
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                65.6.3          py310haa95532_0
sharedmem                 0.3.8                    pypi_0    pypi
simpervisor               0.4                pyhd8ed1ab_0    conda-forge
simplejson                3.18.3                   pypi_0    pypi
sip                       6.6.2           py310hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.9                h6c2663c_0
sniffio                   1.2.0           py310haa95532_1
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.3.2.post1     py310haa95532_0
sphinx                    6.1.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spikeinterface            0.97.0                   pypi_0    pypi
spyder                    5.4.1           py310haa95532_0
spyder-kernels            2.4.1           py310haa95532_0
sqlalchemy                1.3.24                   pypi_0    pypi
sqlite                    3.40.1               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
statsmodels               0.13.5          py310h9128911_1
svt-av1                   1.3.0                h63175ca_0    conda-forge
tbb                       2021.7.0             h59b6b97_0
tbb-devel                 2021.7.0             h59b6b97_0
tblib                     1.7.0              pyhd3eb1b0_0
terminado                 0.17.1          py310haa95532_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
three-merge               0.1.1              pyhd3eb1b0_0
tifffile                  2021.7.2           pyhd3eb1b0_2
tinycss2                  1.2.1           py310haa95532_0
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1           py310haa95532_0
tomlkit                   0.11.1          py310haa95532_0
toolz                     0.12.0          py310haa95532_0
tornado                   6.1             py310h2bbff1b_0
tqdm                      4.64.1          py310haa95532_0
traitlets                 5.7.1           py310haa95532_0
traits                    6.3.2                    pypi_0    pypi
typing-extensions         4.4.0           py310haa95532_0
typing_extensions         4.4.0           py310haa95532_0
tzdata                    2022g                h04d1e81_0
ucrt                      10.0.20348.0         haa95532_0
ujson                     5.4.0           py310hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.14         py310haa95532_0
utfcpp                    3.2.1                haa95532_0
vc                        14.2                 h21ff451_1
viziphant                 0.2.0                    pypi_0    pypi
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
vtk                       9.2.2           qt_py310hafc99e1_201    conda-forge
watchdog                  2.1.6           py310haa95532_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1           py310haa95532_1
websocket-client          0.58.0          py310haa95532_4
whatthepatch              1.0.2           py310haa95532_0
wheel                     0.38.4          py310haa95532_0
widgetsnbextension        3.5.2           py310haa95532_0
win32_setctime            1.1.0              pyhd3eb1b0_0
win_inet_pton             1.1.0           py310haa95532_0
wincertstore              0.2             py310haa95532_2
winpty                    0.4.3                         4
wrapt                     1.15.0                   pypi_0    pypi
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xarray                    2022.11.0       py310haa95532_0
xmltodict                 0.12.0             pyhd3eb1b0_0
xz                        5.2.10               h8cc25b3_1
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
yarl                      1.8.1           py310h2bbff1b_0
zarr                      2.14.2                   pypi_0    pypi
zeromq                    4.3.4                hd77b12b_0
zfp                       0.5.5                hd77b12b_6
zict                      2.1.0           py310haa95532_0
zipp                      3.11.0          py310haa95532_0
zlib                      1.2.13               hcfcfb64_4    conda-forge
zstd                      1.5.2                h19a0ad4_0
```
</details>

**Comment by pantaray** [comment]
Hm, that's strange. I searched around a bit and it seems that sometimes the terminal is not set up correctly to find all required libraries. Does this happen inside a "regular" terminal or in the Anaconda prompt? I just checked macOS and Linux - `mnelab` starts and seems to work there.

**Comment by joschaschmiedt** [comment]
It may be actually be a Windows-specific `mnelab` problem. I just tried a completely clean installation of miniconda and mnelab and got a similar error:
```
(mnelab-test) C:\Users\Joscha Schmiedt>mnelab
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
So nothing to fix here for us except maybe dropping Windows-support for mnelab.

**Comment by pantaray** [comment]
OK, thanks for testing! Since `mnelab` depends on Qt I'd still like to keep it in the "conda bucket" of our environment to ensure that Qt libs are installed alongside it on macOS and Linux (cf. my [comment](https://github.com/neuro-conda/neuro-conda/pull/29#issuecomment-1457999213) in #29). Do you think we should tweak `install.ps1` to manually remove `mnelab` after creating the environment on Windows?

**Comment by joschaschmiedt** [comment]
Maybe a note that it doesn’t work is enough. 

But I guess, we should have a minimal version of #4 soon. Maybe simply importing everything may already uncover severely broken things.

**Comment by pantaray** [comment]
> Maybe simply importing everything may already uncover severely broken things.

Yes, I was thinking along the same lines. Not super accurate but could be a quite good initial test.
