### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by joschaschmiedt** [neuro-conda/neuro-conda#43]
```python
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\pgil\miniconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\pgil\miniconda3\Lib\site-packages\conda_env\cli\main.py", line 56, in do_call
        exit_code = getattr(module, func_name)(arguments, parser)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\pgil\miniconda3\Lib\site-packages\conda\notices\core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\pgil\miniconda3\Lib\site-packages\conda_env\cli\main_create.py", line 164, in execute
        result[installer_type] = installer.install(
                                 ^^^^^^^^^^^^^^^^^^
      File "C:\Users\pgil\miniconda3\Lib\site-packages\mamba\mamba_env.py", line 155, in mamba_install
        transaction.fetch_extract_packages()
    RuntimeError: recursive_directory_iterator::recursive_directory_iterator: The directory name is invalid.: "C:\Users"

`$ C:\Users\pgil\miniconda3\Scripts\mamba create --file C:\Users\pgil\AppData\Local\Temp\neuro-conda-latest.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
CONDA_EXE=C:\Users\pgil\miniconda3\condabin\..\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\pgil\miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\pgil\miniconda3\python.exe
               CONDA_ROOT=C:\Users\pgil\miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\pgil
               LD_PRELOAD=<not set>
PATH=C:\Users\pgil\miniconda3;C:\Users\pgil\miniconda3\Library\mingw-
w64\bin;C:\Users\pgil\miniconda3\Library\usr\bin;C:\Users\pgil\minicon
da3\Library\bin;C:\Users\pgil\miniconda3\Scripts;C:\Users\pgil\minicon
da3\bin;C:\Users\pgil\miniconda3\condabin;C:\Windows\system32;C:\Windo
ws;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0
                          ;C:\Windows\System32\OpenSSH;C:\Program Files\MATLAB\R2023a\bin;C:\Use
rs\pgil\AppData\Local\Microsoft\WindowsApps;C:\Users\pgil\AppData\Loca
                          l\Programs\Microsoft VS Code\bin
PSMODULEPATH=C:\Users\pgil\Documents\WindowsPowerShell\Modules;C:\Program Files\Win
dowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modu
                          les
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\pgil\miniconda3
            shell level : 1
       user config file : C:\Users\pgil\.condarc
 populated config files :
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=23.11.0=0
                          __win=0=0
       base environment : C:\Users\pgil\miniconda3  (writable)
      conda av data dir : C:\Users\pgil\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
https://repo.anaconda.com/pkgs/msys2/win-64
https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\pgil\miniconda3\pkgs
                          C:\Users\pgil\.conda\pkgs
C:\Users\pgil\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\pgil\miniconda3\envs
                          C:\Users\pgil\.conda\envs
C:\Users\pgil\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22631 solver/libmamba co6
          administrator : False
             netrc file : None
           offline mode : False
```

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

**Comment by joschaschmiedt** [comment]
`C:\Users\pgil\miniconda3\Scripts\mamba create --file "C:\Users\pgil\AppData\Local\Temp\neuro-conda-latest.yml"` results in 

```
usage: mamba create [-h] [--clone ENV] (-n ENVIRONMENT | -p PATH) [-c CHANNEL] [--use-local] [--override-channels]
                    [--repodata-fn REPODATA_FNS] [--experimental {jlap,lock}] [--no-lock] [--strict-channel-priority]
                    [--no-channel-priority] [--no-deps | --only-deps] [--no-pin] [--copy] [--no-shortcuts]
                    [--shortcuts-only SHORTCUTS_ONLY] [-C] [-k] [--offline] [--json] [-v] [-q] [-d] [-y]
                    [--download-only] [--show-channel-urls] [--file FILE] [--no-default-packages] [--subdir SUBDIR]
                    [--solver {classic,libmamba}] [--dev]
                    [package_spec ...]
mamba create: error: one of the arguments -n/--name -p/--prefix is required
```

**Comment by joschaschmiedt** [comment]
The actual error is cut off in the original message: 
```
    RuntimeError: recursive_directory_iterator::recursive_directory_iterator: The directory name is invalid.: "C:\Users\pgil\miniconda3\pkgs\qt6-main-6.4.2-h21ac547_5.conda"
```

This is due to an error while downloading:
```
'qt6-main-6.4.2-h21ac547_5.conda extraction failed
```

**Comment by joschaschmiedt** [comment]
It's a known issue: on WIndows: https://github.com/conda/conda/issues/12369

**Comment by joschaschmiedt** [comment]
Explicitly setting the version of qt6-main to 6.4.3 fixes the issue on Windows. 

@pantaray, as this was not caught by our testing and did not happen on all Windows machines, I think we may want to push the use of conda-lock (#5) to have more reproducible environments.

**Comment by pantaray** [comment]
This is very strange. Do you know which package pulls in Qt 6?
